String isDarkTheme = "is_dark_theme";
String isLogedIn = "is_login";
String userToken = "user_token";
String fcmToken = "fcm_token";
String recommendedProductsId = "recommended_product_id";
String product_category = "product_category.json";
const String userDetailsLocalFilePath = "user-details.json";
const String userOrderListFilePath = "user-order-list.json";
const String userFavProduct = "user-fav-product.json";
